// This file is generated by scripts/generate-galleries.mjs — do not edit by hand.
export const generatedGalleries = {
  "marriotts-ridge-rain-garden-mwee-grant": [
    "/projects/marriotts-ridge-rain-garden-mwee-grant/Screenshot 2025-11-14 at 10.23.21 PM.png",
    "/projects/marriotts-ridge-rain-garden-mwee-grant/Screenshot 2025-11-14 at 10.23.49 PM.png"
  ],
  "murray-hill-hoa-invasives": [
    "/projects/murray-hill-hoa-invasives/Screenshot 2025-11-14 at 10.24.31 PM.png",
    "/projects/murray-hill-hoa-invasives/Screenshot 2025-11-14 at 10.24.46 PM.png",
    "/projects/murray-hill-hoa-invasives/Screenshot 2025-11-14 at 10.24.57 PM.png"
  ]
} as Record<string, string[]>;
